### ISSUE TITLE
Parse error when table contains schema

### ISSUE THREAD

**Issue by srghma** [FrigoEU/sqltopurs#1]
using 

```
create table app_public.user_oauths (
  id                 uuid         primary key default uuid_generate_v4()
);
```

with command 

```
sqltopurs -i migrations/0000000002-users/entities/user_oauths/table.up.sql -o migrations/0000000002-users/entities/user_oauths/Table.purs -m Users.Table.purs
```

results in 

```
[nix-shell:~/projects/greenbadger]$ sqltopurs -i migrations/0000000002-users/entities/user_oauths/table.up.sql -o migrations/0000000002-users/entities/user_oauths/Table.purs -m Users.Table.purs
/nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:660
      throw e;
      ^

Error: Error: ParseError: (ParseError "Expected \"(\"" (Position { line: 1, column: 24 }))
    at Object.exports.error (/nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:651:12)
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:18854:148
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:1437:26
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:18855:101
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:1440:26
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:18856:37
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:517:23
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:482:7
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:511:19
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:517:27
    at Object.exports.error (/nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:651:12)
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:18832:101
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:568:11
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:489:7
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:511:19
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:517:27
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:482:7
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:511:19
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:517:27
    at /nix/store/jkgjqvr68ggr2r25waw2pwvqdghh76f4-greenbadger-modules/node_modules/sqltopurs/sqltopurs.js:482:7
```

_____________

using 

```
create table user_oauths (
  id                 uuid         primary key default uuid_generate_v4()
);

```

with same command

results in empty file (error too)

```
module Users.Table.purs where
import Prelude ((<$>), map, (<*>))
import Control.Monad.Except (withExcept)
import Database.Postgres (Client, DB, query, Query(Query), queryOne)
import Control.Monad.Aff (Aff)
import Data.Maybe (Maybe)
import Data.Foreign (F, ForeignError(..))
import Data.Newtype (class Newtype, unwrap)
import Database.Postgres.SqlValue (toSql, readSqlProp, fromSql, class IsSqlValue)

-- Table newtypes

-- CRUD definitions

-- PGSQL Function definitions
```

**Comment by srghma** [comment]
Im thinking, wouldnt it be easier to generate not from parsed file, but from connection 

like this does https://github.com/SweetIQ/schemats

**Comment by srghma** [comment]
I can't believe no one has written something like this for Haskell
